### ISSUE TITLE
jupyter widget `interact` could not be displayed

### ISSUE THREAD

**Issue by sonnyhcl** [Xilinx/PYNQ-ComputerVision#1]
There is some problem with interact widget and I cannot successfully load it. 
Since I can not find this `interact` widget in `Jupyter NBExtensions` tab, what can I do to make it work correctly?

Below is the code and error message:
```python
interact(makeMapCircleZoomAndUpdate, width=fixed(width_widget), 
         height=fixed(height_widget), cx=cx_widget,cy=cy_widget,
         radius=radius_widget,zoom=zoom_widget)
```
> A Jupyter widget could not be displayed because the widget state could not be found. This could happen if the kernel storing the widget is no longer available, or if the widget state was not saved in the notebook. You may be able to create the widget by running the appropriate cells.

**Comment by denolf** [comment]
Hi,

Nothing special should be needed to use the interact widget in a Jupyter notebook, everything has been installed in the lasted PYNQ-Z1 image, currently [version 2.1](http://files.digilent.com/Products/PYNQ/pynq_z1_v2.1.img.zip) 

Can you provide us with some more detailed information so that we more easily reproduce the issue you are reporting?

**Comment by sonnyhcl** [comment]
Sorry for late response. I rerun it in image_v2.1 and it works fine. 

Thanks.

**Comment by denolf** [comment]
Happy to hear it works properly. Closing issue.
